[package]
name = "wifi-connect"
version = "4.2.12"
authors = ["Zahari Petkov <zahari@balena.io>"]
description = "Easy WiFi setup for Linux devices from your mobile phone or laptop"

[dependencies]
network-manager = "0.11"
clap = "2.33"
iron = "0.6"
iron-cors = "0.8"
staticfile = "0.5"
mount = "0.4"
router = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
persistent = "0.4"
params = "0.8"
log = "0.4"
env_logger = "0.8"
nix = "0.19"

[dependencies.error-chain]
version = "0.11"
default-features = false

[profile.release]
lto = true
